{bias_sensitivity: 2, 
 streaming_rate: 100, 
 max_events: 0, 
 subsample_vertical: 0, 
 subsample_horizontal: 0, 
 imu_gyro_scale: 0,
 roi_enabled: True,
 roi_start_column: 122,
 roi_start_row: 42,
 roi_end_column: 517,
 roi_end_row: 437}
